::Short timeframe update exports
sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [Job] ,[Job_Operation] ,[WC_Vendor] ,[Operation_Service] ,[Vendor] ,[Sched_Start] ,[Sched_End] ,[Sequence], [Status] ,[Est_Total_Hrs] FROM [PRODUCTION].[dbo].[Job_Operation] WHERE Last_Updated > DATEADD(MINUTE,-10,GETDATE()) ORDER BY Job_Operation ASC" -o "C:\phoenixapps\csv_files\RunListOps.csv" -W -w 1024 -s "`" -f 65001 -h -1

sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [Job] ,[Customer] ,[Order_Date] ,[Part_Number], [Status] ,[Rev] ,[Description] ,[Order_Quantity] ,[Extra_Quantity] ,[Pick_Quantity] ,[Make_Quantity] ,[Open_Operations] ,[Completed_Quantity] ,[Shipped_Quantity] ,[FG_Transfer_Qty] ,[In_Production_Quantity] ,[Certs_Required] ,[Act_Scrap_Quantity] ,[Customer_PO] ,[Customer_PO_LN] ,[Sched_End] ,[Sched_Start] ,REPLACE (CONVERT(VARCHAR(MAX), Note_Text),CHAR(13)+CHAR(10),' ') ,[Released_Date] ,[User_Values] FROM [PRODUCTION].[dbo].[Job] WHERE Last_Updated > DATEADD(MINUTE,-10,GETDATE()) ORDER BY Job DESC" -o "C:\phoenixapps\csv_files\jobs.csv" -W -w 1024 -s "`" -f 65001 -h -1

sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [Job] ,[Material] ,[Vendor] ,[Description] ,[Pick_Buy_Indicator] ,[Status] FROM [PRODUCTION].[dbo].[Material_Req] WHERE Last_Updated > DATEADD(MINUTE,-10,GETDATE()) ORDER BY Job DESC" -o "C:\phoenixapps\csv_files\material.csv" -W -w 1024 -s "`" -f 65001 -h -1

sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [User_Values] ,[Text1] FROM [PRODUCTION].[dbo].[User_Values] WHERE Text1 IS NOT NULL AND Last_Updated > DATEADD(MINUTE,-10,GETDATE())" -o "C:\phoenixapps\csv_files\shortuservalues.csv" -W -w 1024 -s "`" -f 65001 -h -1
sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [Job_Operation] ,[Employee] ,[Work_Date] ,[Act_Setup_Hrs] ,[Act_Run_Hrs] ,[Act_Run_Qty] ,[Act_Scrap_Qty] ,[Note_Text] FROM [PRODUCTION].[dbo].[Job_Operation_Time] WHERE Last_Updated > DATEADD(DAY,-1,GETDATE()) ORDER BY Job_Operation DESC" -o "C:\phoenixapps\csv_files\operationtime.csv" -W -w 1024 -s "`" -f 65001 -h -1

::Yearly time frame exports
sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [Job] ,[Job_Operation] ,[WC_Vendor] ,[Operation_Service] ,[Sched_Start] ,[Sched_End] ,[Sequence], [Status] ,[Est_Total_Hrs] FROM [PRODUCTION].[dbo].[Job_Operation] WHERE Sched_Start > DATEADD(month,-13,GETDATE()) ORDER BY Job DESC, Sequence" -o "C:\phoenixapps\csv_files\yearlyRunListOps.csv" -W -w 1024 -s "`" -f 65001 -h -1
sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [Job] ,[Customer] ,[Order_Date] ,[Part_Number], [Status],[Rev] ,[Description] ,[Order_Quantity] ,[Extra_Quantity] ,[Pick_Quantity] ,[Make_Quantity] ,[Open_Operations] ,[Shipped_Quantity] ,[Customer_PO] ,[Customer_PO_LN] ,[Sched_End] ,[Sched_Start] ,[Released_Date]  ,REPLACE (CONVERT(VARCHAR(MAX), Note_Text),CHAR(13)+CHAR(10),' ') ,[User_Values] FROM [PRODUCTION].[dbo].[Job] WHERE Sched_Start > DATEADD(month,-13,GETDATE()) ORDER BY Job DESC" -o "C:\phoenixapps\csv_files\yearlyJobs.csv" -W -w 1024 -s "`" -f 65001 -h -1
sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [Job] ,[Material] ,[Vendor] ,[Description] ,[Pick_Buy_Indicator] ,[Status] FROM [PRODUCTION].[dbo].[Material_Req] WHERE Last_Updated > DATEADD(MONTH,-13,GETDATE()) ORDER BY Job DESC" -o "C:\phoenixapps\csv_files\yearlyMat.csv" -W -w 1024 -s "`" -f 65001 -h -1
sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [User_Values] ,[Text1] FROM [PRODUCTION].[dbo].[User_Values] WHERE Text1 IS NOT NULL AND Last_Updated > DATEADD(MONTH,-13,GETDATE())" -o "C:\phoenixapps\csv_files\yearlyuserValues.csv" -W -w 1024 -s "`" -f 65001 -h -1
sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [Job_Operation] ,[Employee] ,[Work_Date] ,[Act_Setup_Hrs] ,[Act_Run_Hrs] ,[Act_Run_Qty] ,[Act_Scrap_Qty] ,[Note_Text] FROM [PRODUCTION].[dbo].[Job_Operation_Time] WHERE Last_Updated > DATEADD(MONTH,-13,GETDATE()) ORDER BY Job_Operation DESC" -o "C:\phoenixapps\csv_files\yearlyoperationtime.csv" -W -w 1024 -s "`" -f 65001 -h -1

::bankstatement history
::sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [Statement_Date] ,[Beginning_Balance] ,[Ending_Balance] ,[Account_Ending_Bal] ,[Outstanding_Checks] ,[Cleared_Deposits] ,[Cleared_Checks] ,[Last_Updated] FROM [PRODUCTION].[dbo].[Bank_History] WHERE Last_Updated > DATEADD(month,-12,GETDATE()) ORDER BY Last_Updated DESC" -o "C:\railsapps\shophawk\app\assets\csv\bankhistory.csv" -W -w 1024 -s "`" -f 65001
::Journal entry - 104 = checking account
::sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [Source] ,[Amount] ,[Transaction_Date] ,[Reference] ,[Last_Updated] ,[Type] ,[Creation_Date] ,[GL_Account] FROM [PRODUCTION].[dbo].[Journal_Entry] WHERE GL_Account = '104' AND Creation_Date > DATEADD(month,-2,GETDATE()) ORDER BY Creation_Date DESC" -o "C:\railsapps\shophawk\app\assets\csv\Journal_Entry.csv" -W -w 1024 -s "`" -f 65001
::open invoice amounts
::sqlcmd -S GEARSERVER\SQLEXPRESS -d PRODUCTION -E -Q "SELECT [Document] ,[Customer] ,[Ship_Via] ,[Terms] ,[Document_Date] ,[Due_Date] ,[Orig_Invoice_Amt] ,[Open_Invoice_Amt] ,[Last_Updated] ,[Invoiced_By] FROM [PRODUCTION].[dbo].[Invoice_Header] WHERE Open_Invoice_Amt > 0 ORDER BY Customer ASC " -o "C:\railsapps\shophawk\app\assets\csv\Open_Invoice_Amounts.csv" -W -w 1024 -s "`" -f 65001